## START: Set by rpmautospec
## (rpmautospec version 0.8.2)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 2;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

Name:           yq
Version:        4.48.1
Release:        %autorelease
Summary:        Portable command-line YAML, JSON, XML, CSV, TOML and properties processor

License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT
URL:            https://github.com/mikefarah/yq
Source0:        https://github.com/mikefarah/yq/%{name}-%{version}.tar.gz

BuildRequires:  go
BuildRequires:  bash-completion
BuildRequires:  fish
BuildRequires:  zsh

%description
Yq is a portable command-line YAML, JSON, XML, CSV, TOML and properties processor.

%package fish-completion
Summary:        Fish shell completion for %{name}
Requires:       %{name} = %{version}-%{release}
Requires:       fish

%description fish-completion
This package contains Fish shell completion for %{name}.

%package zsh-completion
Summary:        Zsh completion for %{name}
Requires:       %{name} = %{version}-%{release}
Requires:       zsh

%description zsh-completion
This package contains Zsh shell completion for %{name}.

%prep
%setup -q -n yq

%build
export GO111MODULE=on
go mod tidy
go mod vendor
go build -mod=vendor -o %{name} .

./%{name} shell-completion bash > %{name}.bash
./%{name} shell-completion fish > %{name}.fish
./%{name} shell-completion zsh  > %{name}.zsh

%install
install -Dpm 0755 %{name} %{buildroot}%{_bindir}/%{name}

install -Dpm 0644 %{name}.bash %{buildroot}%{bash_completions_dir}/%{name}
install -Dpm 0644 %{name}.fish %{buildroot}%{fish_completions_dir}/%{name}.fish
install -Dpm 0644 %{name}.zsh  %{buildroot}%{zsh_completions_dir}/_%{name}

%check
go test ./...

%files
%license LICENSE
%doc README.md
%{_bindir}/yq
%{bash_completions_dir}/%{name}

%files fish-completion
%{fish_completions_dir}/%{name}.fish

%files zsh-completion
%{zsh_completions_dir}/_%{name}

%changelog
## START: Generated by rpmautospec
* Sun Sep 14 2025 Danie de Jager <danie.dejager@gmail.com> - 4.47.2-1
- Initial AL2023 build without go-vendor-tools
- Split fish and zsh completions into subpackages
## END: Generated by rpmautospec
